#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass any JVM options to Gradle and Java processes.
# For example, to pass "-Xms1024m -Xmx2048m" to Gradle, you can use one of the following options:
#
# 1. Add the following line to this file:
#
#    DEFAULT_JVM_OPTS='"-Xms1024m -Xmx2048m"'
#
# 2. Add the following line to your gradle.properties file:
#
#    org.gradle.jvmargs=-Xms1024m -Xmx2048m
#
# 3. Pass it as a command-line argument:
#
#    ./gradlew -Dorg.gradle.jvmargs=-Xms1024m -Xmx2048m <task>
#
# For more information, see https://docs.gradle.org/current/userguide/build_environment.html
#
#*****************************************************************
#
#   !!!!! DO NOT EDIT THIS FILE !!!!!
#
#   This file is generated by the Gradle 'wrapper' task.
#
#   The file is evaluated by the wrapper script on startup and its
#   values are used to invocation of the actual Gradle code.
#
#   This file is checked into version control.
#
#   The format of this file is simple name/value pairs.
#      - Single and double quotes are preserved.
#      - Backslashes are not supported as escape characters.
#      - A # sign at the beginning of a line is a comment.
#
#*****************************************************************

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

# Add sed commands here to transform the classpath passed to the Gradle java command.
# For example, to replace all spaces with underscores:
#
#     CLASSPATH_SED_COMMAND='s/ /_/g'
#
# For example, to remove all jar files from the classpath:
#
#     CLASSPATH_SED_COMMAND='s@/.*\.jar;@;@g'
#

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass any JVM options to Gradle and Java processes.
# For example, to pass "-Xms1024m -Xmx2048m" to Gradle, you can use one of the following options:
#
# 1. Add the following line to this file:
#
#    DEFAULT_JVM_OPTS='"-Xms1024m -Xmx2048m"'
#
# 2. Add the following line to your gradle.properties file:
#
#    org.gradle.jvmargs=-Xms1024m -Xmx2048m
#
# 3. Pass it as a command-line argument:
#
#    ./gradlew -Dorg.gradle.jvmargs=-Xms1024m -Xmx2048m <task>
#
# For more information, see https://docs.gradle.org/current/userguide/build_environment.html
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

# Add sed commands here to transform the classpath passed to the Gradle java command.
# For example, to replace all spaces with underscores:
#
#     CLASSPATH_SED_COMMAND='s/ /_/g'
#
# For example, to remove all jar files from the classpath:
#
#     CLASSPATH_SED_COMMAND='s@/.*\.jar;@;@g'
#
CLASSPATH_SED_COMMAND=''

# Find the project root directory
PROJECT_ROOT_DIR="${APP_HOME}"
while [ ! -f "${PROJECT_ROOT_DIR}/gradlew" ] && [ ! -f "${PROJECT_ROOT_DIR}/gradlew.bat" ] && [ "${PROJECT_ROOT_DIR}" != "/" ]; do
    PROJECT_ROOT_DIR="$(dirname "${PROJECT_ROOT_DIR}")"
done
if [ ! -f "${PROJECT_ROOT_DIR}/gradlew" ] && [ ! -f "${PROJECT_ROOT_DIR}/gradlew.bat" ]; then
    echo "Could not find project root directory."
    exit 1
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            # Use the system limit
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass any JVM options to Gradle and Java processes.
# For example, to pass "-Xms1024m -Xmx2048m" to Gradle, you can use one of the following options:
#
# 1. Add the following line to this file:
#
#    DEFAULT_JVM_OPTS='"-Xms1024m -Xmx2048m"'
#
# 2. Add the following line to your gradle.properties file:
#
#    org.gradle.jvmargs=-Xms1024m -Xmx2048m
#
# 3. Pass it as a command-line argument:
#
#    ./gradlew -Dorg.gradle.jvmargs=-Xms1024m -Xmx2048m <task>
#
# For more information, see https://docs.gradle.org/current/userguide/build_environment.html
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

# Add sed commands here to transform the classpath passed to the Gradle java command.
# For example, to replace all spaces with underscores:
#
#     CLASSPATH_SED_COMMAND='s/ /_/g'
#
# For example, to remove all jar files from the classpath:
#
#     CLASSPATH_SED_COMMAND='s@/.*\.jar;@;@g'
#
CLASSPATH_SED_COMMAND=''

# Find the project root directory
PROJECT_ROOT_DIR="${APP_HOME}"
while [ ! -f "${PROJECT_ROOT_DIR}/gradlew" ] && [ ! -f "${PROJECT_ROOT_DIR}/gradlew.bat" ] && [ "${PROJECT_ROOT_DIR}" != "/" ]; do
    PROJECT_ROOT_DIR="$(dirname "${PROJECT_ROOT_DIR}")"
done
if [ ! -f "${PROJECT_ROOT_DIR}/gradlew" ] && [ ! -f "${PROJECT_ROOT_DIR}/gradlew.bat" ]; then
    echo "Could not find project root directory."
    exit 1
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            # Use the system limit
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" "org.gradle.wrapper.GradleWrapperMain" "$@"

# Start the wrapper
exec "$JAVACMD" "$@"
